### ISSUE TITLE
Add docs to try metrics locally

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pm#153] opened 2015-03-11 17:50 UTC
Add steps a dev would need to first try metrics on their dev box (wherever it fits):

1. install strongloop
2. `cd <my-app>`
3. `slc start`
4. Start collecting metrics: `slc ctl env-set STRONGLOOP_METRICS=statsd://localhost:5140` (defaults to connect to PM on localhost)

**Comment by rmg** [comment] 2015-03-11 17:54
@crandmck heads up, I updated the issue description

**Comment by crandmck** [comment] 2015-03-17 16:58
@sam-github  Will this procedure change with `slc start`?

**Comment by sam-github** [comment] 2015-03-17 22:30
@crandmck steps 1-3 change with `slc start`, of course, but the env-set doesn't.

**Comment by crandmck** [comment] 2015-03-20 21:18
I edited the instructions above to use `slc start` and `slc ctl`.

**Comment by DeniseLee** [comment] 2015-03-23 17:30
@crandmck here is a proposal for slight rearrangement of content of monitoring and some issues/questions.

CURRENT:

Monitoring
	Viewing metrics with Arc
	Setting up monitoring
		Getting metrics without using slc
	Monitoring with slc
		Defining custom metrics
		Object tracking
		Integrating with third-party consoles
			Using third-party APM consoles
		Monitoring the event loop with watchdog
	Metrics API

ISSUES:
1.	Current Monitoring top-level has info about setting up monitoring that is redundant with the section “Setting up monitoring.”
2.	Prereq info about obtaining a SL license comes up in several places. Might be good to just create a prereq section and tell people to go there for info.
3.	No clear benefits section of why to go to Arc vs slc. 
4.	Question: There is a section “Getting metrics without using slc” but I don’t understand the benefit. Wouldn’t you just use arc if you don’t want to use slc?
5.	Question: If u r using slc to monitor, do u use the third-party consoles to view it? Is there a way to use slc, then use Arc to view?

PROPOSED
Monitoring – contains Overview info and when to use Arc vs slc
	Setting up monitoring/prerequisites
		Getting metrics without using slc
Viewing metrics with Arc
	Monitoring with slc
		Defining custom metrics
		Object tracking
		Integrating with third-party consoles

**Comment by crandmck** [comment] 2015-03-23 18:55
I added bullets above to make the hierarchy more apparent. 

Also, you omitted two articles: 
 - [Monitoring the event loop with watchdog](http://docs.strongloop.com/display/SLC/Monitoring+the+event+loop+with+watchdog) 
- [Metrics API](http://docs.strongloop.com/display/SLC/Metrics+API)
 
> Current Monitoring top-level has info about setting up monitoring that is redundant with the section “Setting up monitoring.”

Yes, but I would like to have a "Quick setup" somewhere, because [Setting up monitoring](http://docs.strongloop.com/display/SLC/Setting+up+monitoring) has a lot of gory details that we should keep, but not everyone needs up front to get started.

> Prereq info about obtaining a SL license comes up in several places. Might be good to just create a prereq section and tell people to go there for info.

That sounds good.  Note watchdog requires a special license.  Also, n.b., they are reworking the whole licensing infrastructure so a lot of this will change in a sprint or two.

> No clear benefits section of why to go to Arc vs slc. 

It makes sense to explain this, but you can do a lot both ways and it may come down to if you prefer a GUI or a CLI.

> Question: There is a section “Getting metrics without using slc” but I don’t understand the benefit. Wouldn’t you just use arc if you don’t want to use slc?

This originated with customers who (due to corporate policy or other constraints) could not run their app with `slc run`.  Therefore, they had to alter their code a bit to call `strong-agent` directly.  It's not clear to me if people with such constraints could use Arc instead?  @sam-github Do we need to keep [Getting metrics without using slc](http://docs.strongloop.com/display/SLC/Getting+metrics+without+using+slc)?  As it stands, this appears to be specific to using StatsD--but if we keep it, should it be more general?

> Question: If u r using slc to monitor, do u use the third-party consoles to view it? Is there a way to use slc, then use Arc to view?

You can dump the output to a log file or view it in the console, but in reality, not sure how useful that is.  You should find out if that is a valid use-case.  To visualize the data, AFAIK, you have to use a 3d party console such as DataDog via StatsD.  We used to have a hosted service called StrongOps, which we are EOLing.

Take a look at http://docs.strongloop.com/display/SLC/Getting+started+with+app+monitoring.  I think it might be worth resurrecting some or all of this.

**Comment by DeniseLee** [comment] 2015-03-24 15:32
@sam-github. Please review this page. http://docs.strongloop.com/display/SLC/Monitoring+with+slc+on+a+local+machine. I think we are going to put the work mentioned in the previous comment in a different issue.

**Comment by sam-github** [comment] 2015-03-24 22:11
> which defaults to connect to Process Manger on localhost:

"Manger"?

I would add to that sentence: "and assumes a statsd server is listening on localhost port 5140." You probably want to link to where they can get such a server, and also this is just meant to be a statsd example, I guess? Because it doesn't mention the existence of all the other places metrics can be published, its specific to statsd.


URL formats for metrics are documented here: https://github.com/strongloop/strong-statsd#statsdbackendurl

Personally, the log ones are more useful for an example, because they log to console, so actually work without installing additional software.

Also in http://docs.strongloop.com/display/SLC/Viewing+metrics+with+DataDog  the URL format for --metrics is no longer valid, see above link for valid URLs.

same for: http://docs.strongloop.com/display/SLC/Integrating+with+third-party+consoles

above is also slc run-centric, and its "Use" section just seems to be a duplicate of http://docs.strongloop.com/display/SLC/Monitoring+with+slc+on+a+local+machine, but using slc run instead of slc start.

**Comment by DeniseLee** [comment] 2015-04-08 00:50
Ready for your review, @sam-github. http://docs.strongloop.com/display/SLC/Monitoring+with+slc+on+a+local+machine and http://docs.strongloop.com/display/SLC/Integrating+with+third-party+consoles.

We'll be changing the third-party console info to include viewing metrics on a remote machine.

**Comment by sam-github** [comment] 2015-04-10 18:54
- remove the `Use without slc` section, we don't document how to pull apart our toolset and use the components
- neither the 3rdparty components or local machine sections describe how to do this in production, they just describe `slc start`. Rand's notes describe sl-pm-install, docker.sh should be added to that.

I don't think the split between thirdparty consoles and local machine is useful.

1. It duplicates the (incomplete) section on how to setup the metric destination.
2. syslog and log itself are not thirdparty consoles, but they aren't necessarily local, either, syslog has a protocol to publish/aggregate logs from multiple machines, and the log option could be used to log to a file that is picked up by splunk (for example), or some other console agent.

I'd focus the docs on how to set this up with slc start, and with production, and then enumerate the schemes, and the meaning of the options.

**Comment by crandmck** [comment] 2015-04-14 23:14
OK, I revised all the docs under "Metrics" substantially.   I believe I captured all of Sam's most recent comments above...

Summary:
- Renamed the whole section from "Monitoring" to "Monitoring app metrics" since Arc calls it "Metrics" and there was some lively discussion of whether "metrics" or "monitoring" made more sense.  I just went with both!
- Consolidated all the content that was in "Integrating with third-party consoles" and "Monitoring a local application" into http://docs.strongloop.com/display/SLC/Monitoring+with+slc
- Rearranged order of child pages.

In [Monitoring with slc](http://docs.strongloop.com/display/SLC/Monitoring+with+slc) I struggled a bit to come up with a single term for the value that one gives to STRONGLOOP_METRICS.  I eventually settled on "metrics URL" though as I note in the text, it is not always a real URL (ie. for log & syslog).  I'm open to a different term or even to separating out StatsD/Graphite/Splunk and log/syslog, if that makes more sense.

@sam-github please review and let me know if you want to talk or have specific comments.  Then I will  run by chanda for final review.

**Comment by chandadharap** [comment] 2015-04-17 06:30
@crandmck  Why are we renaming Monitoring to Monitoring app metrics? This was a specific decision.

@sam-github, please assign back to me after you finish.

**Comment by crandmck** [comment] 2015-04-17 17:08
@chandadharap 
> Why are we renaming Monitoring to Monitoring app metrics? This was a specific decision.

Yes, this was my decision and I explained the rationale above:

> Arc calls it "Metrics" and there was some lively discussion of whether "metrics" or "monitoring" made more sense. 

One can make an argument for either rubric: 
- In the Arc UI it is "Metrics" so normally documentation would follow the UI naming.  Otherwise, there is a clear disconnect and possibility of confusion.  Every other Arc module has a fairly clear corresponding section in the docs.
- The actual verb / activity is "Monitoring", i.e. that is what you are doing.  All the other parallel titles are gerunds (e.g. Running, Debugging, Profiling, Scaling, etc.) So that is also a reasonable choice.

I believe for the docs, the best option is to use BOTH, because in fact it describes well what you are actually doing:  You are monitoring your app--and _what_ specifically are you monitoring? **Metrics**.  Therefore, "Monitoring app metrics" seems like the best title to me.  Using either "Monitoring" or "Metrics" alone has drawbacks.  An even more descriptive title would be "Monitoring application performance metrics" but that is far too long to fit in the navigation pane, therefore I believe "Monitoring app metrics" is the best option.

I think it's pretty hard to argue that adding "app metrics" to the "Monitoring" title could cause confusion or detract in any way to the doc usability.  I just don't see the downside.

As the owner of the docs, I made the field decision to make that change. If there is a strong argument  against it, I would like to hear it, and certainly will change it if I am convinced or overruled.

**Comment by chandadharap** [comment] 2015-04-20 05:09
well, i guess my point was Issac specifically made that decision. Arc will be changing to Monitoring in the near future. 

Lets discuss in live.

**Comment by sam-github** [comment] 2015-04-20 17:41
REVIEW COMMENT from Rand
> Does priority affect what information is actually provided? Explain.

Priority and facility is provided along with the message to the syslog server. syslog servers can act on that data. See examples, for example for OS X:

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/syslog.conf.5.html

Commonly they discard messages below particular priorities, and perhaps redirect different facilities to different files.

Anyone familiar with syslog will understand the meaning of this, and why they would want to use non-default values (if they do).

> log and syslog are not URLs

From a very, very technical perspective, I think they are URIs, not URLs, but people mostly use URL not URI. You can read https://danielmiessler.com/study/url_vs_uri/ for the mind-numbing details.

Anyhow, they parse correctly using URL parsers, and you should feel comfortable calling them URLs.

And FWIW, I think putting "Monitoring app metrics" makes great sense as the feature/section title.

**Comment by sam-github** [comment] 2015-04-20 17:42
LGTM

**Comment by crandmck** [comment] 2015-04-20 18:18
OK, thanks.  We can close this issue now AFAIC.

**Comment by chandadharap** [comment] 2015-04-20 18:27
I need to review, will do quickly


On Mon, Apr 20, 2015 at 11:18 AM, Rand McKinney <notifications@github.com>
wrote:

> OK, thanks. We can close this issue now AFAIC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-pm/issues/153#issuecomment-94529030>
> .
>



-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by chandadharap** [comment] 2015-04-20 21:37
@ijroth For now Im going with Monitoring App Metrics until we figure what we call the bucket of things in Arc that aid Monitoring.

**Closed by chandadharap** 2015-04-20 21:37 UTC
Labels: doc
